accounts/urls.py
""" Defines URL patterns for the accounts app. """

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Custom login view overrides Django's built-in login view
    path('login/', views.custom_login, name='login'),
    # Include Django's built-in authentication URLs (login, logout, password management)
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
    # Password reset request page.
    path('forgotten_password/', views.forgotten_password, name='forgotten_password'),
     # Account recovery page.   
     path('recover_account/', views.recover_account, name='recover_account'),
     # Account recovery with uid and token.
    path('recover_account_confirm/<uidb64>/<token>/', views.recover_account_confirm, name='recover_account_confirm'),
    # Endpoint to wipe and reinitialize account (POST only).
    path('wipe_and_reinit/', views.wipe_and_reinit, name='wipe_and_reinit')
    
  
]

password_manager/urls.py
# Defines URL patterns for the password manager

from django.urls import path
from . import views

app_name = 'password_manager'
urlpatterns = [
    # Define your URL patterns here
    path('', views.index, name='index'),
    # Show all stored credentials
    path('credentials/', views.credential, name='credential'),
    # Add a new credential
    path('new_credential/', views.new_credential, name='new_credential'),
    # View a single credential in detail
    path('credentials/<int:credential_id>/', views.view_credential, name='view_credential'),
    # Edit an existing credential
    path('credentials/<int:credential_id>/edit/', views.edit_credential, name='edit_credential'),
    # Delete credential
    path('credentials/<int:credential_id>/delete/', views.delete_credential, name='delete_credential'),
]

pm_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),  # Include URLs from the accounts app
    path('', include('password_manager.urls')),  # Include URLs from the password_manager app
    path("vault-lab/", include("vault_lab.urls"))

    
]

vault_lab/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.vault_lab_index, name='vault_lab_index'),
]

vault_lab/models.py
from django.db import models

# Create your models here.

vault_lab/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def vault_lab_index(request):
    """Home page for the Vault Lab app"""
    return render(request, "vault_lab/home.html")

vault_lab/templates/zk_learning/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stenvard</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <style>
        body {
            background-color: teal;
        }
    </style>
</head>
<body>    
    <!--Navbar-->
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg mb-4 ">
        <div class="container-fluid w-75">
            <a class="navbar-brand" href="{% url 'password_manager:index' %}">Stenvard</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
            data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" 
            aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'password_manager:credential' %}">Credentials</a>
                </li>
            </ul>
            <!-- Account related links-->
            
            <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text me-2">Hello , {{ user.username }}.</span>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a> -
                </li>
                <li class="nav-item">
                    <a class="nav-link"  href="{% url 'accounts:login' %}">Log in</a>
                </li>
                {% endif %}
            </ul>
                <!--Logout link added-->
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <form action="{% url 'accounts:logout' %}" method='post'>
                            {% csrf_token %}
                            <button name="submit" class="btn btn-outline-secondary btn-sm">
                            Log out</button>
                        </form>
                    </a>
                </li>   
                {% endif %}
    </div>
</div>

</nav>
<div class="container flex-container d-flex flex-column">
    <main class="flex-grow-1">
        <div class="pb-2 mb-2">
            {% block page_header %}
            {% endblock page_header %}
        </div>
        <div>
            {% block content %} {% endblock content %}
        </div>    
    </main>
</div>
<footer class="mt-auto py-3 text-center">
    <div class="footer">
        <span class="text-muted">© 2025 Password Manager - Daniel Wilkinson</span>
    </div>
</footer>
</div>
</body>

</html>